### ISSUE TITLE
Upload folder to S3 under Windows path separator

### ISSUE THREAD

**Issue by ads901119** [bobobo1618/docpad-plugin-sunny#18] opened 2014-01-24 14:36 UTC
I have several documents in the generated files which are put into a folder:
```
out/pages/page1.html,
out/pages/page2.html,
...
```

When using Sunny to upload to S3, the files in the 'pages' folder becomes:
```
pages\page1.html
```
(note the backslash in file name instead of creating a folder in S3)

This results in the URL
https://s3-ap-northeast-1.amazonaws.com/MYPROJECT/pages%5Cpage1.html

Could you fix the path separator issue under Windows? Thanks!

**Comment by bobobo1618** [comment] 2016-05-03 03:40
Closing this as it's a duplicate of https://github.com/bobobo1618/docpad-plugin-sunny/issues/20.

Happy to accept a PR but I don't have a WIndows PC to develop on.

**Closed by bobobo1618** 2016-05-03 03:40 UTC
